# Welcome to Jekyll!

# Site Settings
locale: "pt-BR"
title: "Dados, Projetos e Ferramentas"
email: "erick.ribeiro.16@gmail.com"
description: >-
  Cientista de Dados Sênior, atuo no desenvolvimento de projetos utilizando técnicas de Análise Exploratória, Visualização de Dados, Processamento de Linguagem Natural e Machine Learning.
url: "https://erickrribeiro.github.io"
twitter_username: erickrribeiro
github_username: erickrribeiro
minimal_mistakes_skin: default
search: true

twitter:
  username: "erickrribeiro"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes


# Outputting
permalink: /:year/:month/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Manaus

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name   : "Erick R. Ribeiro | M.Sc."
  avatar : "/images/bio-photo.png"
  bio    : "Cientista de Dados - FPFtech"
  location: "Brasil/Manaus"
  links:    
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/erickrribeiro"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/erickrribeiro"
    # - label: "Subscribe"
    #   icon: "fas fa-fw fa-envelope"
    #   url: "https://erickrribeiro.substack.com"
    # - label: "Sponsor"
    #   icon: "fas fa-fw fa-mug-hot"
    #   url: "https://www.buymeacoffee.com/erickrribeiro"
    - label: "Email"
      icon: "fab fa-envelope"
      url: "mailto:erick.ribeiro.16@gmail.com"
    # - label: "Feed"
    #   icon: "fab fa-fw fa-globe"
    #   url: "/feed.xml"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/erickrribeiro"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "images/"
    values:
      image: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
repository: "erickrribeiro/blog-comments"

google_site_verification: "4MVW88X4VwB0SGqNdfcBhp4Xbf1CMSTdLfLzEMP1PFc"

social:
  type:  Person
  name:  Erick R. Ribeiro
  links:
    - "https://github.com/erickrribeiro"
    - "https://www.linkedin.com/in/erickrribeiro"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-MTJXVEWEPE"
    anonymize_ip: false
